name: Update Firewall Blocklist

on:
  schedule:
    # Runs every 6 hours
    - cron:  "0 */6 * * *"
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  update-blocklist:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set PowerShell execution policy
      shell: powershell
      run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force

    - name: Run update script
      shell: powershell
      run: .\update.ps1

    - name: Push changes
      shell: powershell
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add combined_blocklist.txt
        git commit -m "Auto update blocklist $(Get-Date -Format 'yyyy-MM-dd HH:mm')" -ErrorAction SilentlyContinue
        git push
